
import { Card } from '@/components/ui/card';
import { CheckCircle, Activity, RefreshCw } from 'lucide-react';
import { PredictionData } from '@/pages/Index';

interface PredictionResultProps {
  prediction: PredictionData;
  onReupload: () => void;
}

const PredictionResult = ({ prediction, onReupload }: PredictionResultProps) => {
  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 90) return 'text-green-600';
    if (confidence >= 75) return 'text-blue-600';
    if (confidence >= 60) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getConfidenceLabel = (confidence: number) => {
    if (confidence >= 90) return 'Very High';
    if (confidence >= 75) return 'High';
    if (confidence >= 60) return 'Moderate';
    return 'Low';
  };

  const getAcneEmoji = (acneType: string) => {
    switch (acneType.toLowerCase()) {
      case 'blackheads': return '⚫';
      case 'whiteheads': return '⚪';
      case 'papules': return '🔴';
      case 'pustules': return '🟡';
      case 'nodules': return '🟣';
      default: return '✅';
    }
  };

  const getAcneTip = (acneType: string) => {
    switch (acneType.toLowerCase()) {
      case 'blackheads': return 'Use salicylic acid cleansers and avoid over-washing.';
      case 'whiteheads': return 'Gentle exfoliation and non-comedogenic moisturizers help.';
      case 'papules': return 'Apply ice and use anti-inflammatory treatments.';
      case 'pustules': return 'Avoid squeezing. Use benzoyl peroxide cream 2.5%.';
      case 'nodules': return 'Consult a dermatologist for professional treatment.';
      default: return 'Maintain a consistent skincare routine.';
    }
  };

  return (
    <Card className="p-6 bg-gradient-to-r from-green-50 to-blue-50 border-green-200 shadow-lg animate-scale-in">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center">
          <CheckCircle className="w-6 h-6 text-green-600 mr-2" />
          <h3 className="text-xl font-semibold text-gray-800">Analysis Complete</h3>
        </div>
        <button
          onClick={onReupload}
          className="flex items-center text-blue-600 hover:text-blue-800 text-sm font-medium transition-colors"
        >
          <RefreshCw className="w-4 h-4 mr-1" />
          Try Another Image
        </button>
      </div>
      
      <div className="space-y-4">
        <div className="bg-white rounded-lg p-4 shadow-sm">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center">
              <span className="text-3xl mr-3">{getAcneEmoji(prediction.acneType)}</span>
              <span className="text-2xl font-bold text-blue-900">
                {prediction.acneType}
              </span>
            </div>
            <div className="flex items-center">
              <Activity className="w-4 h-4 mr-1 text-gray-500" />
              <span className={`font-semibold ${getConfidenceColor(prediction.confidence)}`}>
                {prediction.confidence}%
              </span>
            </div>
          </div>
          
          <p className="text-gray-600 leading-relaxed mb-3">
            {prediction.description}
          </p>
          
          <div className="mt-3 flex items-center justify-between">
            <span className="text-sm text-gray-500">Confidence Level:</span>
            <span className={`text-sm font-medium ${getConfidenceColor(prediction.confidence)}`}>
              {getConfidenceLabel(prediction.confidence)}
            </span>
          </div>
          
          <div className="mt-2 w-full bg-gray-200 rounded-full h-2">
            <div
              className={`h-2 rounded-full transition-all duration-1000 ease-out ${
                prediction.confidence >= 90 ? 'bg-green-500' :
                prediction.confidence >= 75 ? 'bg-blue-500' :
                prediction.confidence >= 60 ? 'bg-yellow-500' : 'bg-red-500'
              }`}
              style={{ width: `${prediction.confidence}%` }}
            ></div>
          </div>
        </div>
        
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <h4 className="font-semibold text-blue-900 mb-2 flex items-center">
            <span className="mr-2">💡</span>
            Treatment Tip
          </h4>
          <p className="text-sm text-blue-800">
            {getAcneTip(prediction.acneType)}
          </p>
        </div>
        
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3">
          <p className="text-xs text-yellow-800">
            <strong>⚠️ Medical Disclaimer:</strong> This prediction is generated by an AI model and should be used for educational purposes only. 
            Always consult a qualified dermatologist for professional medical advice and treatment.
          </p>
        </div>
      </div>
    </Card>
  );
};

export default PredictionResult;
